### PR TITLE
Don't set background color for such a commonly used class as .container

### PR DESCRIPTION
**Pull request by empurium**
Is there any reason that there's a background color set on .container?

That class name is even used within Bootstrap, and I'm not seeing any visual difference when this color is removed.

However, this class will blast a big red box on top of other content if anybody is using a .container class.

### CODE REVIEW

**Comment by empurium** [comment]
Any possibility of a merge? I don't like having hacked up/modified bower install files :)

**Comment by jsimnz** [comment]
I'm actually just going to remove the entire .container styles, because they seemingly do nothing haha.

Plus a few minor css fixes, like mentioned in #8.

Taking care of it now tho. I know that feeling of annoying modified bower files.

**Comment by jsimnz** [comment]
Added your changes in recent push, https://github.com/jsimnz/nifty.js/commit/22f75a1047ed0bfbb4d811382dbb4b3168195214

**Comment by jsimnz** [comment]
Thanks!

**Comment by empurium** [comment]
Awesome! Thanks again man.

**Pull request closed without merging**
